#!/bin/bash

# Configure nrpe mysql password
if mdata-get nagios_mysql_pass 1>/dev/null 2>&1; then
  NAGIOS_MYSQL_PASSWORD=$(mdata-get nagios_mysql_pass)
  gsed -i \
       "s/nagios-mysql-password/${NAGIOS_MYSQL_PASSWORD}/" \
       /opt/local/etc/nagios/nrpe_local.cfg
fi
